repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: name-tests-test
  - repo: https://github.com/psf/black
    rev: '23.3.0'
    hooks:
      - id: black
  - repo: https://github.com/kynan/nbstripout
    rev: '0.6.1'
    hooks:
      - id: nbstripout
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.97.4
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
